
services:
  postgres:
    image: postgres:alpine
    container_name: chat-app-postgres
    environment:
      POSTGRES_DB: chat-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-app-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: chat-app-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chat-app-network
    restart: unless-stopped

  # chat-app:
  #   build: 
  #     context: .
  #     platforms: 
  #       - linux/arm64
  #   container_name: chat-app-app
  #   env_file:
  #     - .env
  #   environment:
  #     - NODE_ENV=production
  #     - POSTGRES_PRISMA_URL=postgresql://postgres:postgres@postgres:5432/chat-app?connect_timeout=15
  #     - POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@postgres:5432/chat-app
  #     - REDIS_URL=redis://redis:6379
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - chat-app-network
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  chat-app-network:
    driver: bridge
