version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: chatapp-postgres
    environment:
      POSTGRES_DB: chatapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatapp-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: chatapp-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatapp-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  chatapp-network:
    driver: bridge
