name: ci

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    environment:
      name: "${{ github.ref_name == 'main' && 'production' || 'development' }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        id: vars
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          ENV_NAME="${{ github.ref_name == 'main' && 'production' || 'development' }}"
          OWNER_LC="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          REPO_LC="$(echo "$REPO" | tr '[:upper:]' '[:lower:]')"
          echo "image=ghcr.io/${OWNER_LC}/${REPO_LC}-${ENV_NAME}" >> "$GITHUB_OUTPUT"
          echo "env_name=${ENV_NAME}" >> "$GITHUB_OUTPUT"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.vars.outputs.image }}
          tags: |
            type=raw,value=${{ github.run_number }}
          labels: |
            org.opencontainers.image.title=chatapp-${{ steps.vars.outputs.env_name }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}

      - name: Show image reference
        run: |
          echo "Pushed:"
          echo "${{ steps.meta.outputs.tags }}"